// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteEntryFromLogbook = `-- name: DeleteEntryFromLogbook :execresult
DELETE FROM entries WHERE EntryId=$1
`

func (q *Queries) DeleteEntryFromLogbook(ctx context.Context, entryid int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEntryFromLogbook, entryid)
}

const getAllEntriesFromLogbook = `-- name: GetAllEntriesFromLogbook :many
SELECT
EntryId,
Title,
Description,
CreatedOn,
CreatedBy
FROM entries 
WHERE LogbookId=$1
`

type GetAllEntriesFromLogbookRow struct {
	Entryid     int32
	Title       string
	Description string
	Createdon   time.Time
	Createdby   int32
}

func (q *Queries) GetAllEntriesFromLogbook(ctx context.Context, logbookid int32) ([]GetAllEntriesFromLogbookRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntriesFromLogbook, logbookid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEntriesFromLogbookRow
	for rows.Next() {
		var i GetAllEntriesFromLogbookRow
		if err := rows.Scan(
			&i.Entryid,
			&i.Title,
			&i.Description,
			&i.Createdon,
			&i.Createdby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesFromLogbook = `-- name: GetEntriesFromLogbook :many
SELECT
EntryId,
Title,
Description,
CreatedOn,
CreatedBy
FROM entries 
WHERE LogbookId=$1
LIMIT $2
OFFSET $3
`

type GetEntriesFromLogbookParams struct {
	Logbookid int32
	Limit     int32
	Offset    int32
}

type GetEntriesFromLogbookRow struct {
	Entryid     int32
	Title       string
	Description string
	Createdon   time.Time
	Createdby   int32
}

func (q *Queries) GetEntriesFromLogbook(ctx context.Context, arg GetEntriesFromLogbookParams) ([]GetEntriesFromLogbookRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesFromLogbook, arg.Logbookid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesFromLogbookRow
	for rows.Next() {
		var i GetEntriesFromLogbookRow
		if err := rows.Scan(
			&i.Entryid,
			&i.Title,
			&i.Description,
			&i.Createdon,
			&i.Createdby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryFromLogbook = `-- name: GetEntryFromLogbook :one
SELECT
EntryId,
Title,
Description,
CreatedOn,
CreatedBy
FROM entries 
WHERE EntryId=$1
`

type GetEntryFromLogbookRow struct {
	Entryid     int32
	Title       string
	Description string
	Createdon   time.Time
	Createdby   int32
}

func (q *Queries) GetEntryFromLogbook(ctx context.Context, entryid int32) (GetEntryFromLogbookRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryFromLogbook, entryid)
	var i GetEntryFromLogbookRow
	err := row.Scan(
		&i.Entryid,
		&i.Title,
		&i.Description,
		&i.Createdon,
		&i.Createdby,
	)
	return i, err
}

const getLogbookAndOwnerFromEntry = `-- name: GetLogbookAndOwnerFromEntry :one
SELECT 
entries.LogbookId,
logbooks.OwnedBy 
FROM logbooks 
JOIN entries 
ON entries.LogbookId = logbooks.LogbookId
WHERE EntryId=$1
`

type GetLogbookAndOwnerFromEntryRow struct {
	Logbookid int32
	Ownedby   int32
}

func (q *Queries) GetLogbookAndOwnerFromEntry(ctx context.Context, entryid int32) (GetLogbookAndOwnerFromEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getLogbookAndOwnerFromEntry, entryid)
	var i GetLogbookAndOwnerFromEntryRow
	err := row.Scan(&i.Logbookid, &i.Ownedby)
	return i, err
}

const insertNewEntryInLogbook = `-- name: InsertNewEntryInLogbook :execresult
INSERT INTO entries(Title,Description,CreatedBy,LogbookId) VALUES
($1,$2,$3,$4)
`

type InsertNewEntryInLogbookParams struct {
	Title       string
	Description string
	Createdby   int32
	Logbookid   int32
}

func (q *Queries) InsertNewEntryInLogbook(ctx context.Context, arg InsertNewEntryInLogbookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertNewEntryInLogbook,
		arg.Title,
		arg.Description,
		arg.Createdby,
		arg.Logbookid,
	)
}
