// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Entry struct {
	Entryid     int32
	Title       string
	Description string
	Createdon   time.Time
	Createdby   int32
	Logbookid   int32
}

type Logbook struct {
	Logbookid int32
	Title     string
	Ownedby   int32
}

type User struct {
	Userid int32
}
