// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT
FirstName,
LastName
FROM
users
WHERE
Email = $1
`

type GetUserInfoRow struct {
	Firstname string
	Lastname  string
}

func (q *Queries) GetUserInfo(ctx context.Context, email string) (GetUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, email)
	var i GetUserInfoRow
	err := row.Scan(&i.Firstname, &i.Lastname)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT
PasswordHash
FROM
users
WHERE
Email = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, email)
	var passwordhash string
	err := row.Scan(&passwordhash)
	return passwordhash, err
}

const insertNewUser = `-- name: InsertNewUser :execresult
INSERT INTO users(FirstName,LastName,Email,PasswordHash) VALUES
($1,$2,$3,$4)
`

type InsertNewUserParams struct {
	Firstname    string
	Lastname     string
	Email        string
	Passwordhash string
}

func (q *Queries) InsertNewUser(ctx context.Context, arg InsertNewUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertNewUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Passwordhash,
	)
}
