services:
  database:
    container_name: simple_log_database
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: $SIMPLE_LOG_DB_PASSWORD
      POSTGRES_DB: simple_log
