CREATE TABLE users(
    Email VARCHAR(255) NOT NULL PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE logbooks(
    LogbookId SERIAL NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT NOW() NOT NULL,
    OwnedBy VARCHAR(255) NOT NULL REFERENCES users(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE entries(
    EntryId SERIAL NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(5000) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT NOW() NOT NULL,
    CreatedBy VARCHAR(255) NOT NULL REFERENCES users(Email) ON DELETE CASCADE ON UPDATE CASCADE,
    LogbookId INTEGER NOT NULL REFERENCES logbooks(LogbookId) ON DELETE CASCADE ON UPDATE CASCADE
);
